### ISSUE TITLE
Just a comment

### ISSUE THREAD

**Issue by DigitalK** [fivethirtyeight/data#193]
Hi, I am very new to GitHub so sorry if this is not the right place for this comment.
I found this by searching for Unisex names and it really interests me. 
I am a novice coder and would like to know if you have an explanation of the process you went through to make this.  
I'm wondering if I could do something similar using Australian data and in Python? Any info would be much appreciated. Thanks!

**Comment by slamdunking** [comment]
Me the same and anyone know why my hacksilver currency in God of War keeps wiping back to zero no matter how little or lot I do

**Comment by bschneidr** [comment]
The methodology is described in [the FiveThirtyEight article](https://fivethirtyeight.com/features/there-are-922-unisex-names-in-america-is-yours-one-of-them/) and [the underlying R code and data is here so that you can reproduce the analysis](https://github.com/fivethirtyeight/data/tree/master/unisex-names). You can absolutely do something similar with Python, although it's unclear whether there's comparable Australian data available.
