### ISSUE TITLE
Separate TSVs for all March Madness updates?

### ISSUE THREAD

**Issue by Noctem** [fivethirtyeight/data#42]
@dmil Is there any reason that you're adding a new TSV file for every change? Git makes this unnecessary/undesirable. Viewing (or restoring) previous versions of files is easily done with Git (and GitHub), and keeping everything in the same file would make it easier to view what changed in each commit. As Git is designed to track changes to individual files, separating everything defeats some of its purpose and functionality.

If you still want to have multiple files, I would suggest no more than one per round. But the Round of 64 hasn't even started and we already have 7 separate files; so at this rate there will be a lot of clutter soon.

**Comment by mathisonian** [comment]
Thanks @Noctem.

By keeping separate files we hope that it may be useful for readers and those interested in visualizing or analyzing the data to view the changes of the prediction over time. While this is possible with git, it is a bit of a separate use case, and git won't make it easy to use these different versions in a single project. 

Closing this for now (esp. since the tournament is over). Please feel free to open more issues if the way we are doing things don't seem to make sense, and thank you for the feedback.
