### ISSUE TITLE
Race (Unknown-White) in Biopics CSV

### ISSUE THREAD

**Issue by lewisje** [fivethirtyeight/data#50]
I noticed that in the CSV of the biopics, every single line in which the `race_known` column was `Unknown` had the `subject_race` column as `White`; was it that White was the default race, or that you would guess (based on the subject's name and appearance, but without confirmation based on ancestry or self-reporting) that all 197 of the subjects were White? I realize that this wouldn't change the displays, because "Unknown" makes the race column meaningless, but it is a bit curious.

**Comment by andrewflowers** [comment]
Thanks for pointing this out. Where the `race_known` column was `Unknown`, I changed the `subject_race` column to be blank, instead of `White`. 

Our prevailing thought was this: without any indication otherwise and without confirmation on identification or ancestry, the assumption was that they were white. And because we ultimately decided to remove the unknown subjects from the count statistics, it did not effect the analysis. But to avoid confusion, we'll make it blank.

Thanks again for your feedback!
