### ISSUE TITLE
Separate into different repos

### ISSUE THREAD

**Issue by evelynmitchell** [fivethirtyeight/data#51]
24MB is a big chunk, when someone may only want to get the code for one story.

**Comment by AlJohri** [comment]
duplicate of #8

**Comment by mathisonian** [comment]
Thanks @evelynmitchell! We are definitely open to suggestions for the repo structure if there are compelling arguments for a different direction. At this point I think the simplicity and discoverability aspect of having everything in one place outweighs the download size, although as we continue to add more data this could become a more troubling issue.

I'm going to close this so that we can have all of the discussion on repo structure in a centralized place in #8.
